// _macros.typ — shared layout helpers for the daily volume.
//
// Design: every section emits real `#heading()` calls so PDF bookmarks
// appear automatically; visual styling lives in `show heading.where(...)`
// rules applied at the document level. The TOC is hand-built (not
// generated by `#outline()`) so we control which entries it lists and
// how page numbers are formatted, while letting the heading machinery
// drive the bookmark tree.

// ── Font stack ─────────────────────────────────────────────────────
// Names match what the bundled .ttf files actually export (verified
// with fontTools). Newsreader is shipped as a variable font with the
// optical-size + weight axes, so a single family name covers every
// roman/italic/weight combination we use.
#let FONT_TITLE         = ("Big Shoulders Display",)
#let FONT_HEADING_BOLD  = ("Instrument Sans", "Inter", "Helvetica")
#let FONT_HEADING_MED   = ("Instrument Sans Medium", "Instrument Sans", "Inter")
#let FONT_MONO          = ("DM Mono Medium", "DM Mono", "Menlo", "Courier New")
// Family name "Newsreader 16pt" matches the variable font's name-table
// entry (verified via fontTools); plain "Newsreader" silently falls
// back to Libertinus on Linux / Georgia on macOS — unrelated to the
// font being available, the resolver just doesn't bind on the
// typographic-family alias when the file is variable.
#let FONT_BODY_ITALIC   = ("Newsreader 16pt", "Georgia", "Times")
#let FONT_BODY_ROMAN    = ("Newsreader 16pt", "Georgia", "Times")

// ── Colours (mirror pdf_builder.py CSS) ────────────────────────────
#let INK         = rgb("#111111")
#let INK_SOFT    = rgb("#1a1a1a")
#let INK_MED     = rgb("#444444")
#let INK_RULE    = rgb("#555555")
#let INK_HEADER  = rgb("#888888")
#let INK_FAINT   = rgb("#9a9a9a")
#let CREAM       = rgb("#d8dce2")
#let CREAM_SOFT  = rgb(216, 220, 226, 71)   // 0.28 * 255

// ── Visual styles for headings (used by daily.typ via show rules) ──
#let small-heading-block(body) = block(
  below: 8mm,
  stroke: (bottom: 0.3pt + INK),
  inset: (bottom: 1.4mm),
)[
  #set text(font: FONT_HEADING_MED, weight: 500, size: 11pt,
            fill: INK, tracking: 0.22em)
  #upper(body)
]

#let sub-heading(body) = block(below: 6mm)[
  #set text(font: FONT_MONO, size: 7pt, fill: INK_HEADER, tracking: 0.16em)
  #upper(body)
]

// ── Cover page ─────────────────────────────────────────────────────
// `byline` is the centered tagline (EN: "From Remorseless Havoc by
// Simon Roloff", DE: "Aus Remorseless Havoc von Simon Roloff");
// `day_word` is the leading word used on the bottom-left corner ("Day"
// / "Tag"). Both are passed through from `stats.strings` by daily.typ.
#let cover-page(cover_path, day_label, long_date, byline, day_word) = {
  set page(
    paper: "a4",
    margin: 0pt,
    header: none,
    footer: none,
    background: image(cover_path, width: 100%, height: 100%),
  )
  place(
    bottom + left,
    dx: 18mm, dy: -20mm,
    block(width: 174mm)[
      #line(length: 100%, stroke: 0.3pt + CREAM_SOFT)
      #v(6mm)
      #set text(font: FONT_MONO, size: 8pt, fill: CREAM, tracking: 0.22em)
      #grid(
        columns: (1fr, auto, 1fr),
        column-gutter: 10mm,
        align: (left + bottom, center + bottom, right + bottom),
        upper(day_word + " " + day_label),
        upper(byline),
        upper(long_date),
      )
    ],
  )
  []
}

// ── Title-page wrapper (TOC, section-opener, colophon) ─────────────
// Renders `body` as a fresh page with no running header/footer.
#let titlepage(body) = page(
  paper: "a4",
  margin: (top: 22mm, bottom: 16mm, left: 28mm, right: 28mm),
  header: none,
  footer: none,
  body,
)

// ── TOC (custom; we don't use #outline so we control which entries
//     appear and how page numbers render). ─────────────────────────
#let toc(stats) = titlepage[
  // "Contents" is rendered as a real level-1 heading so it bookmarks;
  // the show rule (set in daily.typ) styles it via small-heading-block.
  = #stats.strings.toc_contents
  #label("toc")

  #context {
    let entries = (
      (stats.strings.toc_introduction,                              <intro>),
      (stats.strings.section_opener + " " + stats.day_label,        <section-opener>),
      (stats.strings.toc_vessel_index,                              <vessel-index>),
      (stats.strings.toc_colophon,                                  <colophon>),
    )
    set text(font: FONT_BODY_ROMAN, size: 11pt, fill: INK_SOFT,
             style: "italic", weight: 300)
    for (name, lbl) in entries {
      let hits = query(lbl)
      if hits.len() == 0 { continue }
      let page-num = counter(page).at(hits.first().location()).first()
      block(
        above: 1.6mm, below: 1.6mm,
        stroke: (bottom: 0.05pt + rgb(0, 0, 0, 46)),
        inset: (bottom: 1.6mm),
      )[
        #grid(
          columns: (1fr, auto),
          align: (left + bottom, right + bottom),
          name,
          text(font: FONT_MONO, size: 8pt, fill: INK_RULE,
               style: "normal", weight: 400, tracking: 0.06em)[#page-num],
        )
      ]
    }
  }
]

// ── Section opener ─────────────────────────────────────────────────
// Two-line "Catch of Day / NNN" page in display sizes — the day
// number sits centered below "Catch of Day" so 3- and 4-digit values
// (the project will run for years) both fit comfortably. The heading
// here is a real level-1 heading with the `<section-opener>` label
// so it drives the PDF bookmark (vessels nest under "Catch of Day
// NNN" rather than under "Introduction"); the daily.typ show rule
// detects the label and renders empty for this one heading, since
// the visible big two-line title is drawn by this function itself.
#let section-opener(day_label, label_text: "Catch of Day") = titlepage[
  = #upper(label_text + " " + day_label) <section-opener>

  #v(1fr)
  #align(center)[
    #set text(font: FONT_HEADING_MED, weight: 500, fill: INK)
    // Label and number sit at related sizes — the number is only
    // slightly larger so the title page reads as a balanced two-line
    // statement rather than as a number with a small caption.
    #text(size: 38pt, tracking: 0.16em)[#upper(label_text)]
    #v(8mm, weak: true)
    #text(size: 52pt, tracking: 0.04em)[#day_label]
  ]
  #v(1fr)
]

// ── Introduction ───────────────────────────────────────────────────
// Roman Newsreader at 1.5× line-height (CSS line-height: 1.5):
// par.leading 0.5em on a 10pt body ≈ 15pt total leading. The body
// stays unitalic so the day-specific stats fill in at the same visual
// weight as the surrounding prose; project titles ride italic via
// `_…_` markup as the only inline distinction.
//
// The macro branches on stats.language to render either the EN or DE
// body; the section heading and prose styling are shared. Day-specific
// numbers (long_date, vessels, hours, depletion factor, …) are pulled
// from the same payload fields in both languages.
#let about(stats) = [
  = #stats.strings.toc_introduction
  #label("intro")

  #set text(font: FONT_BODY_ROMAN, weight: 400, size: 10pt,
            fill: INK_SOFT)
  #set par(leading: 0.5em, justify: true, first-line-indent: 0pt)
  // Project titles (Remorseless Havoc, Sea and Spar Between, Moby
  // Dick) — italic only, no weight or size bump; the italic cut is
  // the entire signal.
  #show emph: it => text(style: "italic", fill: INK, it.body)

  // Tier-paragraph helpers — used by both language branches.
  #let _vessel-word-en(n) = if n == 1 [vessel] else [vessels]
  #let _verse-word-en(n) = if n == 1 [verse] else [verses]
  #let _vessel-word-de(n) = if n == 1 [Schiff] else [Schiffe]
  #let _verse-word-de(n) = if n == 1 [Vers] else [Verse]

  #if stats.language == "de" [

    Am #stats.long_date war die industrielle Fischerei mit
    #stats.vessels_active_str Schiffen über alle Ozeane hinweg
    #stats.fishing_hours_str Stunden lang im Einsatz. Ihre Bewegungen
    wurden per Satellit aufgezeichnet und von
    #link("https://globalfishingwatch.org/")[_Global Fishing Watch_]
    (GFW) katalogisiert. Auf der Website
    #link("http://remorselesshavoc.com")[_Remorseless Havoc_] löschte
    jede Stunde ihrer Aktivität algorithmisch generierte
    Gedichtstrophen aus einem digitalen Ozean. An einem einzigen Tag
    wurden #stats.stanzas_caught_str Texte aus dem Meer entnommen und
    können dort nicht mehr gelesen werden. Dieses Dokument enthält ein
    Archiv dieser Löschungen.


    Die Strophen im Meer werden zunächst durch einen Algorithmus
    generiert, der Sprachfragmente von Emily Dickinson und Herman
    Melville zu Strophen kombiniert. Der Algorithmus kann so viele
    Strophen erzeugen, wie es "Fische im Meer" gibt. So schreiben es
    Nick Montfort und Stephanie Strickland, die ihn ursprünglich für
    ihr digitales Literaturprojekt
    #link("https://nickm.com/montfort_strickland/sea_and_spar_between/")[_Sea and Spar Between_]
    entwickelt haben. _Remorseless Havoc_ nimmt die Metapher wörtlich
    und überträgt die Strophen in ein Raster, das den gesamten Globus
    überspannt. Jede Zelle dieses Rasters repräsentiert eine Fläche
    von etwa einem Quadratkilometer (1,1 × 1,1 km am
    Äquatorialmeridian). Das ergibt etwa #stats.ocean_remaining_million
    Millionen Zellen und ebenso viele Strophen, verteilt über die
    Weltmeere. Nach und nach werden die Strophen dann wieder vom
    Programm gelöscht, ausgehend von den Bewegungsdaten der
    industriellen Fischerei.


    Alle technischen Details findet man auch auf der
    #link("https://github.com/roloffsimon/havoc")[GitHub-Seite] dieses
    Projekts, aber die Bewegungsdaten kommen von
    #link("https://globalfishingwatch.org/")[_Global Fishing Watch_].
    Dort analysiert man die Transpondersignale von Schiffen ab einer
    bestimmten Tonnage mit einem Machine-Learning-Algorithmus, der
    charakteristische Wendemanöver, Geschwindigkeitsänderungen und
    Verweildauer-Muster auswertet. GFW identifiziert auf diese Weise
    Fangtätigkeiten von Schiffen, misst sie in Stunden und
    katalogisiert sie in Verbindung mit der GPS-Position. Der
    Algorithmus von _Remorseless Havoc_ löscht die Strophen dann fast
    in Echtzeit aus dem Ozean, da GFW 72 Stunden benötigt, um die
    Satellitendaten zu analysieren — wir sehen also auf der Karte
    Schiffspositionen von vor drei Tagen. Um genau zu sein werden für
    jede gemeldete Fischereistunde #stats.depletion_factor Strophen
    gelöscht — eine Korrektur hin zum tatsächlichen Ausmaß der Jagd im
    Meer, denn GFW geht auf Basis der Gesamtheit ihrer Daten davon
    aus, dass etwa dreimal mehr Stunden Fangtätigkeit in den Meeren
    stattfinden, als es eine konservative Analyse nahelegt (z. B.
    schalten viele Schiffe ihre Transponder aus).


    Die erste Strophe des Gedichts wird vom Programm aus der Zelle
    entnommen, die mit den GPS-Koordinaten des Schiffes übereinstimmt.
    Wenn der Fischfang am selben Ort fortgesetzt wird, wie es in
    vielen Fällen der Fall ist, oder wenn mehrere Schiffe an einer
    Stelle fischen, werden nachfolgende Strophen in einer
    festgelegten Reihenfolge aus dem globalen Pool bezogen, also an
    einer anderen Stelle im Ozean gelöscht. Der Strophenfang jedes
    Schiffes wird dann in diesem Dokument zu einem Gedicht
    zusammengefasst. Dabei ordnet das Programm die Strophen nach
    absteigender lexikalischer Diversität, von hoher zu niedriger
    Shannon-Entropie. Die ersten Strophen sind sprachlich
    reichhaltiger als die letzten, mit vielfältigen Wörtern und
    wenigen Wiederholungen. Im Verlauf des Gedichts verengt sich der
    Wortschatz, die Sätze werden kürzer — ein Bogen von Vielfalt zu
    Verarmung und Erschöpfung.


    // ── Der Schnitt ─────────────────────────────────────────────────
    // Article gender matches the tier-label noun:
    //   selection → Auswahl   (feminine, "eine")
    //   finecut   → Schnitt   (masculine, "ein")
    //   onepiece  → Einzelstück (neuter, "ein")
    #let _de-article = if stats.tier == "selection" [eine] else [ein]
    Der vollständige Fang vom #stats.long_date umfasste
    #stats.fleet_total_str Schiffe und insgesamt
    #stats.stanzas_caught_str gelöschte Verse. Vollständig gedruckt
    würde das Tagesarchiv mehrere tausend Seiten füllen — als
    tägliches Artefakt zu groß für die bescheidene Infrastruktur des
    Projekts. Dieser Band ist daher #_de-article #emph(stats.tier_label):
    #if stats.tier == "selection" [
      ein zufälliges Zehntel der Tagesflotte —
      #stats.selected_vessels_str #_vessel-word-de(stats.selected_vessels)
      und #stats.selected_stanzas_str
      #_verse-word-de(stats.selected_stanzas) — ohne Berücksichtigung
      der Fangmenge gezogen, sodass die Stichprobe die arbeitende
      Flotte abbildet, nicht nur ihre Spitzenfänger.
    ] else if stats.tier == "finecut" [
      ein zufälliges Hundertstel der Tagesflotte —
      #stats.selected_vessels_str #_vessel-word-de(stats.selected_vessels)
      und #stats.selected_stanzas_str
      #_verse-word-de(stats.selected_stanzas) — ein dünnerer Schnitt
      zur Orientierung, ohne Berücksichtigung der Fangmenge gezogen.
    ] else [
      ein einziges, zufällig gezogenes Schiff —
      #stats.selected_stanzas_str
      #_verse-word-de(stats.selected_stanzas) — das minimale Portrait
      des Tages. Das Schiff wurde ohne Berücksichtigung der Fangmenge
      gezogen.
    ]
    Jedes hier erscheinende Schiff wird mit allen seinen Fängen
    gezeigt. Zwei weitere Schnitte werden parallel zu diesem erzeugt
    und sind über das Download-Menü der Projekt-Website abrufbar.


    Das Programm misst die Entleerung des Sprachozeans ab dem ersten
    Tag des Projekts. Ausgehend von der aktuellen Datenlage werden
    jedes Jahr etwa #stats.annual_depletion_pct Prozent des Ozeans in
    _Remorseless Havoc_ geleert und zu Gedichten gemacht. Somit wird
    das Projekt voraussichtlich etwa #stats.runtime_years Jahre
    laufen. Wenn das Meer leer ist, bleibt eine letzte Zelle übrig.
    Ihre Strophen bilden ein letztes Gedicht, dessen Text durch die
    Akkumulation aller vorherigen Löschungen bestimmt wird. Der
    letzte Atemzug des Leviathans, wenn man so will, über den schon
    Herman Melville in Kapitel CV von _Moby Dick_ als Ergebnis der
    systematischen Jagd auf Meeresbewohner nachdachte: "Der streitige
    Punkt ist, ob Leviathan lange eine so weitgestreckte Jagd und ein
    so rücksichtsloses Gemetzel [remorseless havoc] aushalten kann,
    ob er nicht schließlich aus den Gewässern weggewischt werden wird
    und der letzte Wal wie der letzte Mensch seine letzte Pfeife wird
    rauchen müssen, um sich dann selbst mit dem letzten Paffer in
    Dampf aufzulösen."

  ] else [

    On #stats.long_date, industrial fishing vessels —
    #stats.vessels_active_str of them — were active across all oceans
    for #stats.fishing_hours_str hours. Their movements were tracked
    by satellite and catalogued by
    #link("https://globalfishingwatch.org/")[_Global Fishing Watch_]
    (GFW). On the website
    #link("http://remorselesshavoc.com")[_Remorseless Havoc_], every
    hour of their activity erased algorithmically generated poetic
    stanzas from a digital ocean. In a single day,
    #stats.stanzas_caught_str texts were extracted from the sea and
    can no longer be read there. This document contains an archive of
    these deletions.


    The stanzas in the sea are generated by an algorithm that combines
    fragments of text by Emily Dickinson and Herman Melville into
    stanzas. This algorithm can create as many stanzas as there are
    "fish in the sea", according to Nick Montfort and Stephanie
    Strickland, who originally developed it for their digital literary
    work
    #link("https://nickm.com/montfort_strickland/sea_and_spar_between/")[_Sea and Spar Between_].
    _Remorseless Havoc_ takes the metaphor literally and transfers the
    stanzas into a grid spanning the entire globe. Each cell of this
    grid represents an area of about one square kilometre (1.1 × 1.1
    km at the equatorial meridian). This results in approximately
    #stats.ocean_remaining_million million cells and just as many
    stanzas, distributed across the world's oceans. Gradually, the
    stanzas are then deleted by the program based on the movement
    data of industrial fishing vessels.


    All technical details can also be found on this project's
    #link("https://github.com/roloffsimon/havoc")[GitHub page], but
    the movement data comes from
    #link("https://globalfishingwatch.org/")[_Global Fishing Watch_].
    There, the transponder signals from vessels above a certain
    tonnage are analysed using a machine-learning algorithm that
    evaluates characteristic turning manoeuvres, changes in speed,
    and dwell-time patterns. In this way, GFW identifies fishing
    activities by vessels, measures them in hours, and catalogues
    them in conjunction with the GPS position. The _Remorseless
    Havoc_ algorithm then deletes the verses from the ocean almost
    in real time, since GFW requires 72 hours to analyse the
    satellite data — the vessel positions on the map are therefore
    from three days ago. To be precise, #stats.depletion_factor
    stanzas are deleted for every reported hour of fishing — a
    correction to reflect the actual extent of fishing in the sea,
    since GFW assumes, based on the totality of its data, that
    roughly three times as many hours of fishing activity occur in
    the oceans as the conservative analysis indicates (e.g. many
    ships turn off their transponders).


    The first stanza of each vessel's poem is taken from the cell on
    the map that matches the GPS position of the vessel. If fishing
    continues at the same location, as is often the case, or if
    multiple vessels report fishing activity in the same cell,
    subsequent stanzas are drawn from the global pool in a fixed
    order, meaning they are deleted at a different location in the
    ocean. Each vessel's collection of stanzas is then compiled into
    a poem in this document. In doing so, the program arranges the
    stanzas in descending order of lexical diversity, from high to
    low Shannon entropy. The first stanzas are linguistically richer
    than the last, featuring diverse words and few repetitions. As
    the poem progresses, the vocabulary narrows, the sentences
    become shorter — an arc from diversity to impoverishment and
    exhaustion.


    // ── The Cut ──────────────────────────────────────────────────
    The full catch of #stats.long_date came from
    #stats.fleet_total_str vessels and totalled
    #stats.stanzas_caught_str erased verses. Printed in full, the
    day's archive would run to several thousand pages — too large a
    daily artefact for the project's modest infrastructure. This
    volume is therefore a #emph(stats.tier_label):
    #if stats.tier == "selection" [
      a random one-tenth of the day's fleet —
      #stats.selected_vessels_str #_vessel-word-en(stats.selected_vessels)
      and #stats.selected_stanzas_str
      #_verse-word-en(stats.selected_stanzas) — drawn without regard
      to catch size, so the sample represents the working fleet
      rather than only its heaviest hitters.
    ] else if stats.tier == "finecut" [
      a random one-hundredth of the day's fleet —
      #stats.selected_vessels_str #_vessel-word-en(stats.selected_vessels)
      and #stats.selected_stanzas_str
      #_verse-word-en(stats.selected_stanzas) — a thinner cut for
      orientation, drawn without regard to catch size.
    ] else [
      a single randomly chosen vessel — #stats.selected_stanzas_str
      #_verse-word-en(stats.selected_stanzas) — the minimal portrait
      of the day. The vessel was drawn without regard to catch size.
    ]
    Each vessel that appears is shown with all of its catches. Two
    further cuts are produced alongside this one and are reachable
    from the project website's download menu.


    The program measures the depletion of the ocean of language
    starting from the first day of the project. Based on current
    data, approximately #stats.annual_depletion_pct percent of the
    ocean is emptied each year and turned into poems. Thus the
    project is expected to run for about #stats.runtime_years years.
    When the sea is empty, one final cell remains. Its stanzas form
    a final poem, whose text is determined by the accumulated
    sequence of all previous deletions. The Leviathan's last breath,
    so to speak, on which Herman Melville had already speculated in
    Chapter CV of _Moby Dick_ as the result of the systematic
    hunting of sea creatures: "The moot point is, whether Leviathan
    can long endure so wide a chase, and so remorseless a havoc;
    whether he must not at last be exterminated from the waters, and
    the last whale, like the last man, smoke his last pipe, and then
    himself evaporate in the final puff."

  ]
]

// ── One stanza block (4 lines + GPS coords beneath) ─────────────────
// The 4 lines render as a single paragraph with hard linebreaks so we
// don't pick up Typst's between-paragraph spacing — within a stanza,
// only line-leading separates the lines.
//
// Inner gap (`#v` between stanza and coords) and outer gap (`block.below`
// to next stanza) are deliberately asymmetric: the coords float close
// enough to read as the stanza's footer, but the next stanza sits a
// noticeably larger gap below so the boundary stays unambiguous.
#let stanza-block(s) = {
  set text(font: FONT_BODY_ITALIC, weight: 300, size: 8.5pt, style: "italic",
           fill: INK_SOFT)
  set par(leading: 0.30em, justify: false, first-line-indent: 0pt)
  block(breakable: false, below: 5mm)[
    #s.lines.at(0)\
    #s.lines.at(1)\
    #s.lines.at(2)\
    #s.lines.at(3)
    #v(2mm, weak: true)
    #text(font: FONT_MONO, style: "normal", size: 5.4pt, fill: INK_FAINT,
          tracking: 0.06em)[
      #calc.round(s.lat, digits: 2)°, #calc.round(s.lon, digits: 2)°
    ]
  ]
}

// ── One vessel poem: heading + 3-column stanza flow ─────────────────
// `sticky: true` keeps the heading attached to whichever block follows;
// the columns container can break across pages. The heading itself is
// a real level-2 heading so it appears in the PDF outline (bookmarks).
#let render-poem(poem) = {
  block(sticky: true, below: 4.5mm)[
    == #poem.name #label("vessel-" + poem.vkey)
    #h(1.4mm)
    #text(font: FONT_MONO, size: 6.6pt, fill: INK_RULE,
          tracking: 0.18em, baseline: -0.15em)[#upper(poem.flag)]
  ]
  block(below: 8mm)[
    #columns(3, gutter: 6mm)[
      #for s in poem.stanzas [#stanza-block(s)]
    ]
  ]
}

// ── Index of vessels ───────────────────────────────────────────────
#let vessel-index(poems, stats) = [
  = #stats.strings.toc_vessel_index
  #label("vessel-index")
  #sub-heading[#str(poems.len()) entries · ordered alphabetically]
  #context {
    let entries = poems.map(p => (p.name, p.flag, p.vkey))
    entries = entries.sorted(key: e => e.at(0))
    set text(font: FONT_BODY_ROMAN, size: 9pt, fill: INK_SOFT,
             style: "italic", weight: 300)
    columns(2, gutter: 8mm)[
      #for (name, flag, vkey) in entries [
        #block(
          breakable: false,
          stroke: (bottom: 0.08pt + rgb(0, 0, 0, 46)),
          inset: (top: 0.6mm, bottom: 0.6mm),
        )[
          #context {
            let hits = query(label("vessel-" + vkey))
            let page-num = if hits.len() > 0 {
              str(counter(page).at(hits.first().location()).first())
            } else { "—" }
            grid(
              columns: (1fr, auto),
              align: (left + bottom, right + bottom),
              column-gutter: 1.2mm,
              name,
              text(font: FONT_MONO, style: "normal", weight: 400,
                   size: 6.4pt, fill: INK_HEADER, tracking: 0.10em)[
                #upper(flag) · #page-num
              ],
            )
          }
        ]
      ]
    ]
  }
]

// ── Colophon ───────────────────────────────────────────────────────
// Heading is localized via `stats.strings.toc_colophon` (Colophon /
// Impressum). Body branches on `stats.language` so the DE volume reads
// in German end-to-end. The MIT-License footer block at the bottom of
// the page is also language-conditional.
#let colophon(stats) = titlepage[
  = #stats.strings.toc_colophon
  #label("colophon")
  // We rely on the small-heading show rule for visual rendering, then
  // immediately override the page region for the centered colophon
  // body. The h1 is otherwise rendered above the lattice block.
  #v(1fr)
  #align(center, block(width: 130mm)[
    #set text(font: FONT_MONO, weight: 400, size: 8.4pt, fill: INK_SOFT,
              tracking: 0.10em)
    #set par(leading: 0.7em, justify: false)
    #show emph: it => text(style: "normal", fill: INK, it.body)

    #stats.strings.colophon_from#stats.long_date.

    #v(5mm)

    #if stats.language == "de" [
      Tag~#stats.day_label · #upper(stats.tier_label) ·
      #stats.selected_vessels_str / #stats.fleet_total_str Schiffe ·
      #stats.selected_stanzas_str von #stats.stanzas_caught_str Strophen ·
      +#stats.depletion_pct_str% Abbau
    ] else [
      Day~#stats.day_label · #upper(stats.tier_label) ·
      #stats.selected_vessels_str / #stats.fleet_total_str vessels ·
      #stats.selected_stanzas_str of #stats.stanzas_caught_str stanzas ·
      +#stats.depletion_pct_str% depletion
    ]

    #v(5mm)

    #upper(link("http://remorselesshavoc.com")[remorselesshavoc.com])

    #v(5mm)

    #if stats.language == "de" [
      #upper[Der Code des Projekts und Materialien] \
      #upper[sind auf GitHub einsehbar:] \
      #upper(link("https://github.com/roloffsimon/havoc")[github.com/roloffsimon/havoc])
    ] else [
      #upper[All code on GitHub:] \
      #upper(link("https://github.com/roloffsimon/havoc")[github.com/roloffsimon/havoc])
    ]

    #v(2mm)
    #text(fill: INK_HEADER, tracking: 0.4em)[· · ·]
    #v(2mm)

    #if stats.language == "de" [
      #upper[Konzept, Übersetzung der englischsprachigen Texte,] \
      #upper[Umsetzung und Webdesign:] \
      #link("https://roloffsimon.com")[#text(fill: INK)[#upper[Simon Roloff]]].

      #v(5mm)

      #upper[Mit Strophen-Generierung aus] \
      #link("https://nickm.com/montfort_strickland/sea_and_spar_between/")[#upper[_Sea and Spar Between_]] \
      #upper[von Nick Montfort & Stephanie Strickland,] \
      #upper[sowie Fischereidaten von] \
      #link("https://globalfishingwatch.org/")[#upper[_Global Fishing Watch_]].

      #v(5mm)

      #upper[Gesetzt in Big Shoulders Display, Newsreader,] \
      #upper[Instrument Sans und DM Mono.] \
      #upper[Gerendert am #stats.rendered_utc.]
    ] else [
      #upper[Concept, implementation and webdesign:] \
      #link("https://roloffsimon.com")[#text(fill: INK)[#upper[Simon Roloff]]].

      #v(5mm)

      #upper[With Stanza Generation from] \
      #link("https://nickm.com/montfort_strickland/sea_and_spar_between/")[#upper[_Sea and Spar Between_]] \
      #upper[by Nick Montfort & Stephanie Strickland,] \
      #upper[and Fishing Data from] \
      #link("https://globalfishingwatch.org/")[#upper[_Global Fishing Watch_]].

      #v(5mm)

      #upper[Set in Big Shoulders Display, Newsreader,] \
      #upper[Instrument Sans, and DM Mono.] \
      #upper[Rendered #stats.rendered_utc.]
    ]
  ])
  #v(1fr)
  #place(bottom + center)[
    #block(width: 130mm)[
      #set text(font: FONT_MONO, size: 6.4pt, fill: INK_RULE, tracking: 0.06em)
      #set par(leading: 0.55em, justify: true)
      #show emph: it => text(fill: INK_MED, it.body)
      #if stats.language == "de" [
        © Simon Roloff. Der Text dieses Dokuments steht unter der
        MIT-Lizenz und darf wiederverwendet, angepasst und
        weiterverbreitet werden, sofern _Remorseless Havoc_ (Simon
        Roloff, 2026) als Quelle angegeben wird. Die einzelnen Strophen
        stammen aus _Sea and Spar Between_ (Montfort & Strickland,
        2010, BSD-Lizenz).
      ] else [
        © Simon Roloff. The text of this document is released under
        the MIT License and may be reused, adapted and redistributed,
        provided that _Remorseless Havoc_ (Simon Roloff, 2026) is
        credited as the source. The individual stanzas are derived
        from _Sea and Spar Between_ (Montfort & Strickland, 2010, BSD
        License).
      ]
    ]
  ]
]
