// _macros.typ — shared layout helpers for the daily and weekly volumes.
//
// Design: every section emits real `#heading()` calls so PDF bookmarks
// appear automatically; visual styling lives in `show heading.where(...)`
// rules applied at the document level. The TOC is hand-built (not
// generated by `#outline()`) so we control which entries it lists and
// how page numbers are formatted, while letting the heading machinery
// drive the bookmark tree.

// ── Font stack ─────────────────────────────────────────────────────
// Names match what the bundled .ttf files actually export (verified
// with fontTools). Newsreader is shipped as a variable font with the
// optical-size + weight axes, so a single family name covers every
// roman/italic/weight combination we use.
#let FONT_TITLE         = ("Big Shoulders Display",)
#let FONT_HEADING_BOLD  = ("Instrument Sans", "Inter", "Helvetica")
#let FONT_HEADING_MED   = ("Instrument Sans Medium", "Instrument Sans", "Inter")
#let FONT_MONO          = ("DM Mono Medium", "DM Mono", "Menlo", "Courier New")
#let FONT_BODY_ITALIC   = ("Newsreader", "Georgia", "Times")
#let FONT_BODY_ROMAN    = ("Newsreader", "Georgia", "Times")

// ── Colours (mirror pdf_builder.py CSS) ────────────────────────────
#let INK         = rgb("#111111")
#let INK_SOFT    = rgb("#1a1a1a")
#let INK_MED     = rgb("#444444")
#let INK_RULE    = rgb("#555555")
#let INK_HEADER  = rgb("#888888")
#let INK_FAINT   = rgb("#9a9a9a")
#let CREAM       = rgb("#d8dce2")
#let CREAM_SOFT  = rgb(216, 220, 226, 71)   // 0.28 * 255

// ── Visual styles for headings (used by daily.typ via show rules) ──
// Keep these as standalone functions so weekly.typ can reuse them.
#let small-heading-block(body) = block(
  below: 8mm,
  stroke: (bottom: 0.3pt + INK),
  inset: (bottom: 1.4mm),
)[
  #set text(font: FONT_HEADING_MED, weight: 500, size: 11pt,
            fill: INK, tracking: 0.22em)
  #upper(body)
]

#let sub-heading(body) = block(below: 6mm)[
  #set text(font: FONT_MONO, size: 7pt, fill: INK_HEADER, tracking: 0.16em)
  #upper(body)
]

// ── Cover page ─────────────────────────────────────────────────────
#let cover-page(cover_path, day_label, long_date) = {
  set page(
    paper: "a4",
    margin: 0pt,
    header: none,
    footer: none,
    background: image(cover_path, width: 100%, height: 100%),
  )
  place(
    bottom + left,
    dx: 18mm, dy: -20mm,
    block(width: 174mm)[
      #line(length: 100%, stroke: 0.3pt + CREAM_SOFT)
      #v(6mm)
      #set text(font: FONT_MONO, size: 8pt, fill: CREAM, tracking: 0.22em)
      #grid(
        columns: (1fr, auto, 1fr),
        column-gutter: 10mm,
        align: (left + bottom, center + bottom, right + bottom),
        upper("Day " + day_label),
        upper("From Remorseless Havoc by Simon Roloff"),
        upper(long_date),
      )
    ],
  )
  []
}

// ── Title-page wrapper (TOC, section-opener, colophon) ─────────────
// Renders `body` as a fresh page with no running header/footer.
#let titlepage(body) = page(
  paper: "a4",
  margin: (top: 22mm, bottom: 16mm, left: 28mm, right: 28mm),
  header: none,
  footer: none,
  body,
)

// ── TOC (custom; we don't use #outline so we control which entries
//     appear and how page numbers render). ─────────────────────────
#let toc(stats) = titlepage[
  // "Contents" is rendered as a real level-1 heading so it bookmarks;
  // the show rule (set in daily.typ) styles it via small-heading-block.
  = Contents
  #label("toc")

  #context {
    let entries = (
      ("Introduction",                                  <intro>),
      ("Catch of Day " + stats.day_label,               <section-opener>),
      ("Index of vessels",                              <vessel-index>),
      ("Colophon",                                      <colophon>),
    )
    set text(font: FONT_BODY_ROMAN, size: 11pt, fill: INK_SOFT,
             style: "italic", weight: 300)
    for (name, lbl) in entries {
      let hits = query(lbl)
      if hits.len() == 0 { continue }
      let page-num = counter(page).at(hits.first().location()).first()
      block(
        above: 1.6mm, below: 1.6mm,
        stroke: (bottom: 0.05pt + rgb(0, 0, 0, 46)),
        inset: (bottom: 1.6mm),
      )[
        #grid(
          columns: (1fr, auto),
          align: (left + bottom, right + bottom),
          name,
          text(font: FONT_MONO, size: 8pt, fill: INK_RULE,
               style: "normal", weight: 400, tracking: 0.06em)[#page-num],
        )
      ]
    }
  }
]

// ── Section opener ─────────────────────────────────────────────────
// Two-line "Catch of Day / NNN" page in display sizes — the day
// number sits centered below "Catch of Day" so 3- and 4-digit values
// (the project will run for years) both fit comfortably. The heading
// here is a real level-1 heading with the `<section-opener>` label
// so it drives the PDF bookmark (vessels nest under "Catch of Day
// NNN" rather than under "Introduction"); the daily.typ show rule
// detects the label and renders empty for this one heading, since
// the visible big two-line title is drawn by this function itself.
#let section-opener(day_label) = titlepage[
  = #upper("Catch of Day " + day_label) <section-opener>

  #v(1fr)
  #align(center)[
    #set text(font: FONT_HEADING_MED, weight: 500, fill: INK)
    // Label sits as the smaller line; the day number below dominates.
    // 4-digit numbers (year-N projects) fit at 160pt within the 154mm
    // content width with room to spare.
    #text(size: 38pt, tracking: 0.16em)[#upper("Catch of Day")]
    #v(16mm, weak: true)
    #text(size: 160pt, tracking: 0.04em)[#day_label]
  ]
  #v(1fr)
]

// ── Introduction ───────────────────────────────────────────────────
#let about(stats) = [
  = Introduction
  #label("intro")

  #set text(font: FONT_BODY_ITALIC, weight: 300, size: 10pt,
            fill: INK_SOFT, style: "italic")
  #set par(leading: 0.55em, justify: true, first-line-indent: 0pt)
  #show emph: it => text(style: "normal", weight: 500, fill: INK,
                          it.body)

  On #stats.long_date, the industrial fishing fleet worldwide operated
  for #stats.fishing_hours_str hours with #stats.vessels_active_str
  vessels across the oceans. Their movements were recorded by satellite,
  interpreted as patterns of turns and drifts and catalogued by
  #link("https://globalfishingwatch.org/")[_Global Fishing Watch_] as
  fishing events. On the website
  #link("http://remorselesshavoc.com")[_Remorseless Havoc_], each hour
  of that activity erased algorithmically generated language from a
  digital ocean. In a single day, #stats.stanzas_caught_str texts were
  lifted out of the sea and can no longer be read there. This document
  is the archive of that day's erasure.

  #parbreak()

  The texts are generated by an algorithm from
  #link("https://nickm.com/montfort_strickland/sea_and_spar_between/")[_Sea and Spar Between_],
  a work of digital literature developed by Nick Montfort and Stephanie
  Strickland in 2010: a grid of algorithmically generated stanzas,
  navigable in the browser, combinatorially assembled from language
  fragments by Emily Dickinson and Herman Melville. About 225 trillion
  stanzas extend in the browser almost endlessly in every direction,
  triggering the vertigo of combinatorics in an infinity with no
  practically reachable boundary from finite source material. Montfort
  and Strickland say their work contains as many verses as there are
  "fish in the sea."

  #parbreak()

  _Remorseless Havoc_ takes that metaphor literally and maps the
  combinatory ocean onto the real seas of the world. It transfers
  Montfort and Strickland's stanzas into a grid spanning the whole
  globe with landmasses spared. Each cell represents a space of about
  one square kilometre, 1.1 × 1.1 km at the equatorial meridian. This,
  obviously, leaves out the majority of stanzas from the originally
  generated trillions. Approximately #stats.ocean_remaining_million
  million verses remain distributed across the world's oceans.
  Subsequently, a second erasure follows, driven by the real fishing
  operations of real-world ships searching for actual fish in the sea.

  #parbreak()

  Their movement data is taken from the _Global Fishing Watch_ Events
  API, which the website of the project calls once a day. GFW
  identifies fishing activity from AIS transponder signals — the
  automatic identification system that ships above a certain tonnage
  are required to carry — using a machine-learning classifier that
  distinguishes fishing behaviour from transit by reading
  characteristic turns, speed changes, and dwell patterns. The Events
  API reports only discrete, high-confidence fishing events. GFW's
  broader 4Wings dataset, which aggregates all AIS positions classified
  as fishing, reports approximately 3.4 times more activity. This is
  why the algorithm of _Remorseless Havoc_ erases #stats.depletion_factor
  stanzas per fishing hour — a correction toward the actual scale of
  extraction from the seas.

  #parbreak()

  The first stanza of each vessel's poem is taken from the GPS
  coordinate of the fishing event — the geographic cell where the
  vessel operates, if it still contains language. When fishing
  continues at the same location, as it does in many cases, subsequent
  stanzas are drawn from a global pool in fixed order. Each vessel's
  catch is then ordered, to be published in this document, from high to
  low Shannon entropy, which is a measure of lexical diversity. The
  first stanzas are the linguistically richest with varied words and
  few repetitions. As the sequence progresses, the vocabulary narrows,
  more words recur, mirroring an arc from diversity to monotony and
  exhaustion.

  #parbreak()

  Depletion of the project's ocean is measured from the project's first
  day — each percentage point earned by real vessels, almost in real
  time (GFW takes 72 hours to analyze the satellite data, so what we
  can actually see are movements from three days before). At the
  current rate, approximately #stats.annual_depletion_pct percent of
  the ocean of language in _Remorseless Havoc_ is emptied each year.
  Thus the project is estimated to run for roughly #stats.runtime_years
  years, until this sea is emptied. At that point, one last cell will
  remain, and its stanzas will form one last poem determined by the
  accumulated sequence of all deletions before it. The "final puff" if
  you will, that Melville foresaw when speculating about the ecological
  extinction of sea creatures in chapter CV of _Moby Dick_, "Does the
  Whale's Magnitude Diminish? — Will He Perish?", from which the title
  of this project is taken.
]

// ── One stanza block (4 lines + GPS coords beneath) ─────────────────
// The 4 lines render as a single paragraph with hard linebreaks so we
// don't pick up Typst's between-paragraph spacing — within a stanza,
// only line-leading separates the lines.
#let stanza-block(s) = {
  set text(font: FONT_BODY_ITALIC, weight: 300, size: 8.5pt, style: "italic",
           fill: INK_SOFT)
  set par(leading: 0.30em, justify: false, first-line-indent: 0pt)
  block(breakable: false, below: 3mm)[
    #s.lines.at(0)\
    #s.lines.at(1)\
    #s.lines.at(2)\
    #s.lines.at(3)
    #v(0.5mm, weak: true)
    #text(font: FONT_MONO, style: "normal", size: 5.4pt, fill: INK_FAINT,
          tracking: 0.06em)[
      #calc.round(s.lat, digits: 2)°, #calc.round(s.lon, digits: 2)°
    ]
  ]
}

// ── One vessel poem: heading + 3-column stanza flow ─────────────────
// `sticky: true` keeps the heading attached to whichever block follows;
// the columns container can break across pages. The heading itself is
// a real level-2 heading so it appears in the PDF outline (bookmarks).
#let render-poem(poem) = {
  block(sticky: true, below: 4.5mm)[
    == #poem.name #label("vessel-" + poem.vkey)
    #h(1.4mm)
    #text(font: FONT_MONO, size: 6.6pt, fill: INK_RULE,
          tracking: 0.18em, baseline: -0.15em)[#upper(poem.flag)]
  ]
  block(below: 8mm)[
    #columns(3, gutter: 6mm)[
      #for s in poem.stanzas [#stanza-block(s)]
    ]
  ]
}

// ── Index of vessels ───────────────────────────────────────────────
#let vessel-index(poems) = [
  = Index of vessels
  #label("vessel-index")
  #sub-heading[#str(poems.len()) entries · ordered alphabetically]
  #context {
    let entries = poems.map(p => (p.name, p.flag, p.vkey))
    entries = entries.sorted(key: e => e.at(0))
    set text(font: FONT_BODY_ROMAN, size: 9pt, fill: INK_SOFT,
             style: "italic", weight: 300)
    columns(2, gutter: 8mm)[
      #for (name, flag, vkey) in entries [
        #block(
          breakable: false,
          stroke: (bottom: 0.08pt + rgb(0, 0, 0, 46)),
          inset: (top: 0.6mm, bottom: 0.6mm),
        )[
          #context {
            let hits = query(label("vessel-" + vkey))
            let page-num = if hits.len() > 0 {
              str(counter(page).at(hits.first().location()).first())
            } else { "—" }
            grid(
              columns: (1fr, auto),
              align: (left + bottom, right + bottom),
              column-gutter: 1.2mm,
              name,
              text(font: FONT_MONO, style: "normal", weight: 400,
                   size: 6.4pt, fill: INK_HEADER, tracking: 0.10em)[
                #upper(flag) · #page-num
              ],
            )
          }
        ]
      ]
    ]
  }
]

// ── Colophon ───────────────────────────────────────────────────────
#let colophon(stats) = titlepage[
  = Colophon
  #label("colophon")
  // We rely on the small-heading show rule for visual rendering, then
  // immediately override the page region for the centered colophon
  // body. The h1 is otherwise rendered above the lattice block.
  #v(1fr)
  #align(center, block(width: 130mm)[
    #set text(font: FONT_MONO, weight: 400, size: 8.4pt, fill: INK_SOFT,
              tracking: 0.10em)
    #set par(leading: 0.7em, justify: false)
    #show emph: it => text(style: "normal", fill: INK, it.body)

    Catch of the Day from #stats.long_date.

    #v(5mm)

    Day~#stats.day_label · #stats.vessels_active_str vessels ·
    #stats.stanzas_caught_str stanzas ·
    +#stats.depletion_pct_str% depletion

    #v(5mm)

    #upper(link("http://remorselesshavoc.com")[remorselesshavoc.com])

    #v(5mm)

    #upper[All code on GitHub:] \
    #upper(link("https://github.com/roloffsimon/havoc")[github.com/roloffsimon/havoc])

    #v(2mm)
    #text(fill: INK_HEADER, tracking: 0.4em)[· · ·]
    #v(2mm)

    #upper[Concept, implementation and webdesign:] \
    #link("https://roloffsimon.com")[#text(fill: INK)[#upper[Simon Roloff]]].

    #v(5mm)

    #upper[With Stanza Generation from] \
    #link("https://nickm.com/montfort_strickland/sea_and_spar_between/")[#upper[_Sea and Spar Between_]] \
    #upper[by Nick Montfort & Stephanie Strickland,] \
    #upper[and Fishing Data from] \
    #link("https://globalfishingwatch.org/")[#upper[_Global Fishing Watch_]].

    #v(5mm)

    #upper[Set in Big Shoulders Display, Newsreader,] \
    #upper[Instrument Sans, and DM Mono.] \
    #upper[Rendered #stats.rendered_utc.]
  ])
  #v(1fr)
  #place(bottom + center)[
    #block(width: 130mm)[
      #set text(font: FONT_MONO, size: 6.4pt, fill: INK_RULE, tracking: 0.06em)
      #set par(leading: 0.55em, justify: true)
      #show emph: it => text(fill: INK_MED, it.body)
      © Simon Roloff. The text of this document is released under the
      MIT License and may be reused, adapted and redistributed, provided
      that _Remorseless Havoc_ (Simon Roloff, 2026) is credited as the
      source. The individual stanzas are derived from
      _Sea and Spar Between_ (Montfort & Strickland, 2010, BSD License).
    ]
  ]
]
